import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/_globals.scss";
import App from "@/components/appInits/App";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Elie Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <App>{children}</App>
      </body>
    </html>
  );
}
